
# Name of website
title: Open-data resources

# Your name to show in the footer
author: M.H.K. Hesselbarth

# Theme
theme: jekyll-theme-primer

github:
  is_project_page: false

# Social networks
social-network-links:
  github: Allgeier-Lab
  twitter: AllgeierLab
  
# Select which social network share links to show in posts
share-links-active:
  github: true
  twitter: true
