# Open-data resources

title: Open-data resources

# social network links to display
social-network-links:
  github: AllgeierLab
  twitter: AllgeierLab
  
share-links-active:
  twitter: true
  github: true

# icon in URL
avatar: "img/icon.jpeg"

# make icon round
round-avatar: true

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - README.md
  - CODE_OF_CONDUCT.md
  - LICENSE.md

theme: jekyll-theme-architect
